version: '3.8'

services:
  # ----------- database services
  # redis:
  #   image: redis:latest
  #   container_name: redis_db
  #   networks:
  #     - spaceai-fmproj-network
  #   ports:
  #     - "6379:6379"

  # postgres:
  #   image: postgres:latest
  #   container_name: postgres_db
  #   environment:
  #     POSTGRES_DB: mydatabase
  #     POSTGRES_USER: myuser
  #     POSTGRES_PASSWORD: mypassword
  #   networks:
  #     - spaceai-fmproj-network
  #   ports:
  #     - "5432:5432"

  # cassandra:
  #   image: cassandra:latest
  #   container_name: cassandra_db
  #   networks:
  #     - spaceai-fmproj-network
  #   ports:
  #     - "9042:9042"

  mysql:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: agridb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword 
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - spaceai-fmproj-network
    ports:
      - "3306:3306"
    restart: always
  
  # ----------- code microservice-services services
  api_fs:
    container_name: api_fs
    build:
      context: ./api-fs/.
    ports:
      - 5000:5000
    volumes: 
      - ./api-fs/.:/app/.
    command: >
      sh -c "flask run --host=0.0.0.0 --port=5000 --debug"
    depends_on:
      - mysql
    networks:
      - spaceai-fmproj-network


networks:
  spaceai-fmproj-network:
    driver: bridge
    

